### ISSUE TITLE
Add a new note field for metastatic sites

### ISSUE THREAD

**Issue by davisart** [hl7-eu/pcsp#32]
We require a new single field note for metastatic sites description in Secondary Cancer Condition

**Comment by gcangioli** [comment]
are you looking for an additional textual field in the logical model for each site or for each metastasis ?

**Comment by gcangioli** [comment]
in this case could we consider the Body Location Qualifier extension (text attribute) to convey this additional text ?

**Comment by davisart** [comment]
I need a clarification from Gaslini "Descrizione aggiuntiva sedi di metastasi"

**Comment by davisart** [comment]
Yesterday I had a call with Giacomo Cavalca (Gaslini) to also talk about this issue, but I need more inputs to solve this issue

**Comment by gcangioli** [comment]
> Yesterday I had a call with Giacomo Cavalca (Gaslini) to also talk about this issue, but I need more inputs to solve this issue

inputs from whom ?

**Comment by davisart** [comment]
more information requested by email to Monica Muraca (Gaslini)

**Comment by davisart** [comment]
Monica confirmed us that “additional description of metastases sites” is a new body site (fourth metastasis site)

**Comment by gcangioli** [comment]
not totally clear what I should do :-).. let's fix a call

**Comment by davisart** [comment]
this is my understanding:
![metastasis](https://user-images.githubusercontent.com/78952233/197953088-249a1a10-0228-4689-9f31-b4bfbd17f2ec.png)

**Comment by gcangioli** [comment]
If I well understood the requirement is alreeady covered by the current profile.
you can have a fourth bodySite where only the .text element is filled.

@davisart : can I close the issue ?
