### ISSUE TITLE
Radiotherapy resources

### ISSUE THREAD

**Issue by davisart** [hl7-eu/pcsp#33]
We need a container for radiotherapy resources that includes the first part of Radiotherapy form from "Center of treatment" field to "End date" field.

All the radiotherapy resouces shoud have different types of field depending on the type of radiotherapy.
- For classic type of radiotherapy/external beam (33195004	External beam radiotherapy) all the fields.
- For brachytherapy type of radiotherapy (SNOMED code: 152198000	Brachytherapy) it is not required the boost, the shield and number of fractions.
- For metabolic/radionuclide type of radiotherapy (SNOMED code: 399315003 Radionuclide therapy) it is not required the body site, the boost and the shield.
The fields that are required in children resources are: body site,dose,cycle number/number of fractions, position.

Alternatevely if we have only one body site or there aren't body sitse, as in "metabolic/radionuclide type of radiotherapy", this container can also manage all the data without any child.

**Comment by gcangioli** [comment]
..sorry but it is not clear to me what are you exactly looking for... :-(

**Comment by davisart** [comment]
- [ ] please [bodySite](https://build.fhir.org/ig/hl7-eu/pcsp/StructureDefinition-Procedure-radiotheraphy-eu-pcsp-definitions.html#Procedure.bodySite) should be set "0..*" (bodysite is not required for metabolic/radionuclide type of radiotherapy)
- [ ] in https://build.fhir.org/ig/hl7-eu/pcsp/StructureDefinition-Observation-totalDoseRad-eu-pcsp.html [bodySite](https://build.fhir.org/ig/hl7-eu/pcsp/StructureDefinition-Observation-totalDoseRad-eu-pcsp-definitions.html#Observation.bodySite) should be set 0..*  (bodysite is not required for metabolic/radionuclide type of radiotherapy)
- [ ] procedure related dose 0...* [relatedDose](https://build.fhir.org/ig/hl7-eu/pcsp/StructureDefinition-Procedure-radiotheraphy-eu-pcsp-definitions.html#Procedure.extension:relatedDose)

**Comment by gcangioli** [comment]
Closed by https://github.com/hl7-eu/pcsp/commit/c785a5c5d75addf42b781e164dd9e0742d94ad64
