### ISSUE TITLE
Missing mapped elements (Davide's email July 26th)

### ISSUE THREAD

**Issue by gcangioli** [hl7-eu/pcsp#34]
From Davide's email, July 26th

non riusciamo a trovare alcuni campi sulla documentazione.

- [ ]  Diagnosi
  - [ ] “Altri quadri clinici, non associati al tumore”

- [x] Recidiva/Progressione (prima della prima fine elettiva delle cure)/ Recidiva/progressione (AFTER):
  - [x] “Tipo” (locale, distante, combinata)
  - [x] “Se distante, sede delle metastasi” (testo libero)

- [x]  Chirurgia maggiore
  - [x] “Se si, descrivere la protesi” (interna/esterna)

- [x]  Chemioterapia
  - [x] Il tipo di dose (dose cumulativa somministrata/stimata/non noto)
  - [x] "I dosaggi indicati sono incompleti" (direttamente connesso al campo "Steroidi ad alte dosi continuative per più di quattro settimane?")
  - [x] “Motivazioni” campo di testo collegato a “I dosaggi indicati sono incompleti” 

- [ ]  Non abbiamo indicazioni sulla scheda "Medical suggestion"
(now moved to #37 )

**Comment by gcangioli** [comment]
> * [ ]   Diagnosi 
>   * [ ]  “Altri quadri clinici, non associati al tumore”

See https://github.com/hl7-eu/pcsp/issues/35#issue-1340438986

**Comment by gcangioli** [comment]
> * [ ]  Recidiva/Progressione (prima della prima fine elettiva delle cure)/ Recidiva/progressione (AFTER):

See https://github.com/hl7-eu/pcsp/issues/36

**Comment by gcangioli** [comment]
> * [ ]   Major Surgery  
>   * [ ]  If yes - Please define if prosthesis is internal (e.g. titanium bone) or external (e.g. artificial limb). Also in this case, details should be reported in the surgery description 

See https://build.fhir.org/ig/hl7-eu/pcsp/StructureDefinition-MajorSurgery-definitions.html#MajorSurgery.prothesis.deviceType
MajorSurgery.prothesis.deviceType , mapped into the (https://build.fhir.org/ig/hl7-eu/pcsp/StructureDefinition-Procedure-surgery-eu-pcsp-definitions.html#Procedure.usedCode)

**Comment by gcangioli** [comment]
> * [ ]   Chemioterapia
>   
>   * [ ]  Il tipo di dose (dose cumulativa somministrata/stimata/non noto)

See [Chemotherapy.productAdministration.cumulativeDose.measureType](https://build.fhir.org/ig/hl7-eu/pcsp/StructureDefinition-Chemotherapy-definitions.html#Chemotherapy.productAdministration.cumulativeDose.measureType mapped into [Observation.method](https://build.fhir.org/ig/hl7-eu/pcsp/StructureDefinition-Observation-totalDoseRad-eu-pcsp-definitions.html#Observation.method)
>   * [ ]  "I dosaggi indicati sono incompleti" (direttamente connesso al campo "Steroidi ad alte dosi continuative per più di quattro settimane?")
>   * [ ]  “Motivazioni” campo di testo collegato a “I dosaggi indicati sono incompleti”

•         Chemioterapia
            - Il tipo di dose (dose cumulativa somministrata/stimata/non noto) 



            - "I dosaggi indicati sono incompleti" (direttamente connesso al campo "Steroidi ad alte dosi continuative per più di quattro settimane?") 

completionStatus => Observation.conformsTo(http://hl7.eu/fhir/ig/pcsp/StructureDefinition/Observation-cumulativeDoseChemo-eu-pcsp).where(status = #preliminary)

            - “Motivazioni” campo di testo collegato a “I dosaggi indicati sono incompleti” 
            
statusReason => Observation.conformsTo(http://hl7.eu/fhir/ig/pcsp/StructureDefinition/Observation-cumulativeDoseChemo-eu-pcsp).extension('http://hl7.org/fhir/StructureDefinition/event-statusReason')

**Comment by gcangioli** [comment]
> * [ ]   Non abbiamo indicazioni sulla scheda "Medical suggestion"

Documented into the [medicalSuggestion section](https://build.fhir.org/ig/hl7-eu/pcsp/StructureDefinition-Composition-surpass-eu-pcsp-definitions.html#Composition.section.section:medicalSuggestion)

**Comment by davisart** [comment]
> > * [x]    Major Surgery  
> >   
> >   * [x]   If yes - Please define if prosthesis is internal (e.g. titanium bone) or external (e.g. artificial limb). Also in this case, details should be reported in the surgery description
> 
> See https://build.fhir.org/ig/hl7-eu/pcsp/StructureDefinition-MajorSurgery-definitions.html#MajorSurgery.prothesis.deviceType MajorSurgery.prothesis.deviceType , mapped into the [usedCode](https://build.fhir.org/ig/hl7-eu/pcsp/StructureDefinition-Procedure-surgery-eu-pcsp-definitions.html#Procedure.usedCode)

[ ] please add "unknown"
[ ] fix external device description

**Comment by davisart** [comment]
> > * [x]    Chemioterapia
> >   
> >   * [x]   Il tipo di dose (dose cumulativa somministrata/stimata/non noto)
> 
> See [Chemotherapy.productAdministration.cumulativeDose.measureType](https://build.fhir.org/ig/hl7-eu/pcsp/StructureDefinition-Chemotherapy-definitions.html#Chemotherapy.productAdministration.cumulativeDose.measureType) mapped into [Observation.method](https://build.fhir.org/ig/hl7-eu/pcsp/StructureDefinition-Observation-cumulativeDoseChemo-eu-pcsp-definitions.html#Observation.method)
 

- [ ] please add "unknown"

**Comment by davisart** [comment]
> > * [x]    Non abbiamo indicazioni sulla scheda "Medical suggestion"
> 
> Documented into the [medicalSuggestion section](https://build.fhir.org/ig/hl7-eu/pcsp/StructureDefinition-Composition-surpass-eu-pcsp-definitions.html#Composition.section.section:medicalSuggestion)


- [ ] section appears as follow:
![medical_suggestions](https://user-images.githubusercontent.com/78952233/187173190-b2255b69-89e0-4c5e-9d9b-49907efc16dc.png)

**Comment by gcangioli** [comment]
> > * [x]    Non abbiamo indicazioni sulla scheda "Medical suggestion"
> 
> Documented into the [medicalSuggestion section](https://build.fhir.org/ig/hl7-eu/pcsp/StructureDefinition-Composition-surpass-eu-pcsp-definitions.html#Composition.section.section:medicalSuggestion)

This part seems not to be just textual, but a little structured  (date of prescription, single text field with all the medications;  other textual data).

@davisart :  to be clarified if a textual export of this information could be enough at this stage, or if we need a more structured management of these data But may require to add more.

**Comment by davisart** [comment]
Medical Suggestion contains all medication prescribed that are not linked to tumors, in these cases each drug needs a date (not possible for now in the platform). Medical Suggestion will be covered by a new section "Follow Up" not yet present in the platform. Gaslini will tell us on how to proceed, in the meantime I suggest to skip this part

**Comment by gcangioli** [comment]
remaining issues documented by #34 and #35
