### ISSUE TITLE
Valueset for laterality of body site in Primary Cancer Condition Profile

### ISSUE THREAD

**Issue by StefanBeyer** [hl7-eu/pcsp#38]
We just noticed that for the laterality of the body site a different valueset is used in the current PCSP UI than the FHIR IG: http://build.fhir.org/ig/hl7-eu/pcsp/StructureDefinition-Condition-primaryCancer-eu-pcsp.html

The IG and also the current implementation of the PCSP FHIR interface seem to support the mCode valueset (https://build.fhir.org/ig/HL7/fhir-mCODE-ig//ValueSet-mcode-laterality-qualifier-vs.html). The valueset that is used in the PCSP UI does exist in the IG, but it seems to be unused here (http://build.fhir.org/ig/hl7-eu/pcsp/ValueSet-laterality-qualifier-lrub-vs.html).

When playing around with the API I noticed, that some values of the mCode are actually mapped, but I could not find a way to map the other values, that we might also decide to transmit from our bioregistry, especially as this is a mandatory field. Sending the loinc codes or the data absent codes, does not seem to have an effect other than the code being displayed on the UI for informational purposes.

As we will not use the UI for Austria and like to transmit all of our data via the FHIR API, I was wondering how we can transmit the last three values?

- 51440002	Right and left (qualifier value) -> Bilateral
- 399488007	Midline (qualifier value) -> (no effect)
- 24028007	Right (qualifier value) -> Right
- 7771000	Left (qualifier value) -> Left
- ??? -> N/A
- ??? -> Monolateral unknown side
- ??? -> NK

On the other side, I was wondering why the field is mandatory in the UI and if the field is actually required for the generation of the care plan. If not, we might also decide not to send this data at all, or with the other valueset. In the original Excel datasheet we received, it is not marked as required. Why are there now more fields required on the PCSP UI than in the sheet?

**Comment by gcangioli** [comment]
The value set included is provided as preferred value set to show what are possible laterality values that can be used, but you can add more if you need too including exceptional values as N/A or NK.

If you think useful for clarity we can include as preferred value set one describing only those used by the UI nad leave the wider as alternative binding.

**Comment by StefanBeyer** [comment]
Yes I think this would be great. It was my general assumption that all values that are selectable in the UI are also part of the IG (and that they are also imported accordingly, when we send them to the FHIR server), but maybe I was wrong here.

Obviously I don't have anything against alternative bindings. Ideally I could at least send all selectable values (that are actually interpreted by the system) in some coding, and for clarity a restricted binding would of course be very helpful.

I guess this would also trigger a minor adaption of the current PSCP implementation, as the other valueset (http://build.fhir.org/ig/hl7-eu/pcsp/ValueSet-laterality-qualifier-lrub-vs.html) is currently not interpreted and/or mapped to the UI selection? Or am I getting something wrong here?

**Comment by gcangioli** [comment]
> On the other side, I was wondering why the field is mandatory in the UI and if the field is actually required for the generation of the care plan. If not, we might also decide not to send this data at all, or with the other valueset. In the original Excel datasheet we received, it is not marked as required. Why are there now more fields required on the PCSP UI than in the sheet?

I supposed it was not :-) ... @davisart ?

**Comment by gcangioli** [comment]
https://github.com/hl7-eu/pcsp/commit/b47a1f57fb47f5a072db9585e07a6cd85e4b75e7

**Comment by davisart** [comment]
we confirm this field is not mandatory for the purpose of Care Plan generation
it is mandatory only in the UI
