### ISSUE TITLE
Relapse during FTL logical model mapping

### ISSUE THREAD

**Issue by StefanBeyer** [hl7-eu/pcsp#41]
For the relapse during [FTL logical model](http://build.fhir.org/ig/hl7-eu/pcsp/StructureDefinition-RelapseDuringFLT-mappings.html), the following mapping is given for the RelapseDuringFLT root element: `.extension(http://hl7.eu/fhir/ig/pcsp/StructureDefinition/ResourceRelatedInfo-eu-pcsp).conformsTo(http://hl7.eu/fhir/ig/pcsp/StructureDefinition/Observation-cumulativeDoseRad-eu-pcsp)`

It is unclear to me which profile/resource this relates to and I can't figure out why the cumulative radiation dose is part of this mapping.

In the [artifacts index page](http://build.fhir.org/ig/hl7-eu/pcsp/artifacts.html) for the Primary Cancer condition, the following description is given:
> "... This profile should be also used for documenting primary cancer relapses.".

For relapses after FLT this is clear to me, especially as the mapping explicitly states it.

Does this also apply for relapses during FLT? If it also applies for relapses during FLT, it seems a little bit odd to me, that the mapping for e.g. site differs from the relapse after FTL model and that certain elements or mappings are named differently.

Could you please clarify? Maybe I am missing something.

**Comment by StefanBeyer** [comment]
Update: I found a hint in the [FLT logical model mapping](http://build.fhir.org/ig/hl7-eu/pcsp/StructureDefinition-FrontLineTreatment-mappings.html):

isProgressionRelapseDuringFLT:
`
Condition.conformsTo('http://hl7.eu/fhir/ig/pcsp/StructureDefinition/Condition-primaryCancer-eu-pcsp').where( (extension('http://hl7.eu/fhir/ig/pcsp/StructureDefinition/condition-previousStatus').valueCode = #replaspe or #recurrence) and ( onsetDateTime < Procedure.conformsTo('http://hl7.eu/fhir/ig/pcsp/StructureDefinition/Procedure-flt-eu-pcsp').performedPeriod.end) ).exists()
`

So it seems that the resource to be used is actually the same. Maybe we could clarify this in the relapse during FLT logical model mapping.

**Comment by gcangioli** [comment]
added in the profile description "This profile should be also used for documenting primary cancer relapses during or after FLT" I hope this will help

**Comment by StefanBeyer** [comment]
Thank you for adding the clarification. Still, I think that the URL in the [FLT mapping ](http://build.fhir.org/ig/hl7-eu/pcsp/StructureDefinition-RelapseDuringFLT-mappings.html) (or the entire mapping?) is wrong: 


RelapseDuringFLT -> `.extension(http://hl7.eu/fhir/ig/pcsp/StructureDefinition/ResourceRelatedInfo-eu-pcsp).conformsTo(http://hl7.eu/fhir/ig/pcsp/StructureDefinition/Observation-cumulativeDoseRad-eu-pcsp)`

I guess it should be something like http://hl7.eu/fhir/ig/pcsp/StructureDefinition/Condition-primaryCancer-eu-pcsp instead of http://hl7.eu/fhir/ig/pcsp/StructureDefinition/Observation-cumulativeDoseRad-eu-pcsp ?

**Comment by gcangioli** [comment]
fix the mapping

**Comment by gcangioli** [comment]
https://github.com/hl7-eu/pcsp/commit/edfd58c7a885a8f78f3368da7ae09b38c7f00a53
