### ISSUE TITLE
Administrative Gender Other Description

### ISSUE THREAD

**Issue by StefanBeyer** [hl7-eu/pcsp#42]
In the PCSP platform for the administrative gender [other](http://hl7.org/fhir/R4/codesystem-administrative-gender.html#administrative-gender-other) it is possible to enter a description of the gender. How can such a description be encoded in the patient FHIR resource? I cannot find a respective element in the [Patient PCSP resource](http://build.fhir.org/ig/hl7-eu/pcsp/StructureDefinition-Patient-eu-pcsp.html).

**Comment by gcangioli** [comment]
@StefanBeyer @davisart : suggestions ?

**Comment by StefanBeyer** [comment]
I don't think we really need to send this data from our point of view. However, the field is currently marked as required in the PCSP UI (if the gender other is selected), so I'm not really sure.

If we should send it, I guess the extension would be fine.

**Comment by davisart** [comment]
we confirm we cannot add "other" specification in FHIR Patient resource, we agree with Stefan to add it in a specific extension

**Comment by gcangioli** [comment]
https://github.com/hl7-eu/pcsp/commit/380cf00ceb00befa280798619783331f3c861d38
