### ISSUE TITLE
SCT GVHD Mapping for Start and End Dates

### ISSUE THREAD

**Issue by StefanBeyer** [hl7-eu/pcsp#43]
In the logical model for [SCT](http://build.fhir.org/ig/hl7-eu/pcsp/StructureDefinition-StemCellTransplantation-mappings.html), the gvhd element is mapped to the [Condition: GvHD](http://build.fhir.org/ig/hl7-eu/pcsp/StructureDefinition-Condition-gvhd-eu-pcsp.html) profile. Both `startDate` and `endDate `elements for acute and chronic GvHD are mapped to  `.effectivePeriod.start` and  `.effectivePeriod.end` respectively. However, the condition resource does not define an `effectivePeriod `element (only an `onsetPeriod` or `abatementPeriod`).

Which is the correct element to use here?

**Comment by gcangioli** [comment]
Thanks for pointing this out @StefanBeyer, there are two issue there :
(1) the typo in the mapping (easy to fix) ... effective[x] doesn not exist in the Condition...
(2) the used element is an onSet should be a dateTime and not Period; the same for the abatement[x]

**Comment by gcangioli** [comment]
see https://github.com/hl7-eu/pcsp/commit/52bc23db3bf747e907edf1acc7e83b6f98a627a8
