### ISSUE TITLE
Radiotherapy shielding position

### ISSUE THREAD

**Issue by StefanBeyer** [hl7-eu/pcsp#44]
In the logical model of the Radiotherapy the [position of the shielding](http://build.fhir.org/ig/hl7-eu/pcsp/StructureDefinition-Radiotherapy-definitions.html#Radiotherapy.target.shielding.position) is a text field ("Describe the positioning of shielding"). It is mapped to the bodySite element of the [Radiotherapy Shield](http://build.fhir.org/ig/hl7-eu/pcsp/StructureDefinition-Procedure-radiotheraphyShield-eu-pcsp.html) procedure profile. However, the bodySite element there has a required binding to the [Radiotherapy sites](http://build.fhir.org/ig/hl7-eu/pcsp/ValueSet-vs-radiotherapy-pcsp.html) value set.

According to the definition of [required](http://hl7.org/fhir/R4/terminologies.html#required), it is not acceptable to only provide the text element for a coding in this case ("text can be provided as well, and is always recommended, but is not an acceptable substitute for the required code"). If this binding would not exist, we would have simply used the text element without any code.

Is this a copy/paste from the other profiles or should we e.g. send the same code here as for the site?

Maybe you could clarify.

**Comment by davisart** [comment]
maybe it is possible to use "NullFlavor" (a question for Giorgio)

**Comment by gcangioli** [comment]
added 'as-text' as exceptional value .
@davisart , @StefanBeyer other value sets where it should be added ?

**Comment by gcangioli** [comment]
https://github.com/hl7-eu/pcsp/commit/a936f8385ef4618bd7baa64704428c93da54221f

**Comment by StefanBeyer** [comment]
> added 'as-text' as exceptional value . @davisart , @StefanBeyer other value sets where it should be added ?

Currently I don't see the need anywhere else.
