### ISSUE TITLE
CarePlan - "Note" and "Planned for" for each recommendation and "Chronic conditions"

### ISSUE THREAD

**Issue by davisart** [hl7-eu/pcsp#45]
We need to map "Note" and "Planned for" fields that clinician can input for each recommendation in the Care Plan form
For each Care Plan it is also possible to insert "Chronic conditions", we didn't find it in the IG
http://build.fhir.org/ig/hl7-eu/pcsp/StructureDefinition-CarePlan-eu-pcsp.html

**Comment by gcangioli** [comment]
Let's fix a call to address your request

**Comment by gcangioli** [comment]
Note => does CarePlan.activity.detail.description fit for purpose ?

**Comment by gcangioli** [comment]
to be done:

- [ ] define a model for CarePlan (see https://github.com/hl7-eu/pcsp/issues/25)
- [ ] clarify how to manage Note
- [ ] clarify what 'Planned for' stands for ..

**Comment by davisart** [comment]
> Note => does CarePlan.activity.detail.description fit for purpose ?
yes, for each activity (recommendation) we can use "CarePlan.activity.detail.description"
for care plan note we can use "CarePlan.note"
we ticked "clarify how to manage Note"

to summarize it's needed to have:
1)  "Chronic conditions" for each care plan
2) "Planned for" for each recommendation

**Comment by gcangioli** [comment]
there are two kinds of notes:
(1) chronic conditions. Single text
(2) textual notes for the plan

First option: use supportingInfo finding a way to distinguish by the risk factors.

Use notes: by defining an extension to filter the kind of note

**Comment by gcangioli** [comment]
Planned for => scheduledString

**Comment by gcangioli** [comment]
> Planned for => scheduledString

added

**Comment by gcangioli** [comment]
> there are two kinds of notes: (1) chronic conditions. Single text (2) textual notes for the plan
> 
> First option: use supportingInfo finding a way to distinguish by the risk factors.
> 
> Use notes: by defining an extension to filter the kind of note

Implemented the second option

**Comment by gcangioli** [comment]
https://github.com/hl7-eu/pcsp/commit/298eb2b08422f8a74eacab78928bb780401ec13a
