### ISSUE TITLE
Radiotherapy Resource

### ISSUE THREAD

**Issue by davisart** [hl7-eu/pcsp#46]
1) We need "Not known" for "Code" http://build.fhir.org/ig/hl7-eu/pcsp/ValueSet-vs-radiotherapyType-eu-pcsp.html
2) We don't understand if "Code" in Radiotherapy Boost (http://build.fhir.org/ig/hl7-eu/pcsp/StructureDefinition-Procedure-radiotheraphyBoost-eu-pcsp.html) can have more than one type of radiotherapy (i.e. Boost radiation therapy and External beam radiotherapy). Because 'Boost Radiation Therapy' is a fixed value, we also need to add a 'Radiotherapy Type' field with the following possible values of 'External beam radiotherapy', 'Brachytherapy', or 'unknown'."

**Comment by gcangioli** [comment]
> 1. We need "Not known" for "Code" http://build.fhir.org/ig/hl7-eu/pcsp/ValueSet-vs-radiotherapyType-eu-pcsp.html

Added

**Comment by gcangioli** [comment]
https://github.com/hl7-eu/pcsp/commit/a936f8385ef4618bd7baa64704428c93da54221f

**Comment by davisart** [comment]
1. ok, thank you!
2. no, for external beam, boost can be: external beam, brachytherapy, NK. For brachytherapy and metabolic radionuclide, boost is missing

**Comment by gcangioli** [comment]
In this case:
- an option could be that of using in one code.coding "Boost radiation therapy" and in a second one the kind of "boost therapy" 
- or use the code for the type of radiotherapy and the category to convey both "Radiotherapy" and "Boost radiation therapy" .

obviously none of them are back compatible changes

**Comment by davisart** [comment]
for us both solutions are feasible, we prefer the second one, please let us know, thank you!

**Comment by gcangioli** [comment]
Ok let's go for the second then...

**Comment by gcangioli** [comment]
https://github.com/hl7-eu/pcsp/commit/d888035fd84d5d30bf587f0f22a0de748fc6a956
