### ISSUE TITLE
Other Info Resource

### ISSUE THREAD

**Issue by davisart** [hl7-eu/pcsp#47]
- Field  "> 10 transfusions"

For import we can use "boundsRange.low" or "count" field.
1) Maybe this value should be ">10", and not ">9" as indicated in the IG.
2) How many transfusions is it possible to include for the single diagnosis? In this case should we need to sum the number of tranfusions?

For the export:
1) How we can set this value? can we set 11? And which one between "boundsRange.low" and "count"?
2) Just a confirm: we will export a single resource for transfusions

**Comment by gcangioli** [comment]
> 1. Maybe this value should be ">10", and not ">9" as indicated in the IG.

I'll change into >10

**Comment by gcangioli** [comment]
> 2\. How many transfusions is it possible to include for the single diagnosis? In this case should we need to sum the number of tranfusions?

the solution allows for a certain flexibility :

- you can have one procedure describing how many transfusions have been made (using the procedure-performedTiming)
- or to have one procedure per transfusion. In this case, procedure-performedTiming will not be used and you count the transfusion procedure associated to a single condition

To be checked with pilot the solution that they are going to use (most likely the first one if they have aggregated data)

**Comment by gcangioli** [comment]
> For the export:
> 
> 1. How we can set this value? can we set 11? And which one between "boundsRange.low" and "count"?
> 2. Just a confirm: we will export a single resource for transfusions

If you are capturing the information '> 10' and nothing else then you have only one procedure with boundsRange.low = '11' (= 10 if >= 10)
If you are capturing the exact number of transfusions then you can use count =#transfusions

**Comment by gcangioli** [comment]
@davisart and @StefanBeyer  let me know if I can consider this issue closed

**Comment by gcangioli** [comment]
description as '> 10' has been changed in https://github.com/hl7-eu/pcsp/commit/ac9c347c07e2fa2937de55b4002fe27955860384 as you suggested

However the description I have says "Please specify if patient received 10 or more than 10 transfusions during therapy" so 10 is included so it should be  >9...

**Comment by davisart** [comment]
thank you Giorgio, I'm sorry: "≥" is correct as mentioned in the description, so we will use boundsRange.low = '10' 
- [ ] roll back to >9

if there are more than one transfusion, "count" value is the total sum or the single number of transfusion?

**Comment by gcangioli** [comment]
count says how many times this procedure has been repeated...not sure to have correctly understood your question..

**Comment by gcangioli** [comment]
https://github.com/hl7-eu/pcsp/commit/86d0e3317af15c15c2b49ef26a6a566f1fe6cf89
