### ISSUE TITLE
Stem Cell Transplantation Resource

### ISSUE THREAD

**Issue by davisart** [hl7-eu/pcsp#48]
Regarding GVHD profylaxis, we need to know if "Acute GVHD" and "Chronic" GVHD go both within the same "coding" father (as shown in the example below) or they should have multiple "coding" fathers.

Example:
`
"code": {

        "coding": [

            {

                "system": "[http://snomed.info/sct"](http://snomed.info/sct%22),

                "code": "234646005",

                "display": "Graft-versus-host disease"

            },

            {

                "system": "[http://snomed.info/sct"](http://snomed.info/sct%22),

                "code": "402355000",

                "display": "Acute graft-versus-host disease"

            },

            {

                "system": "[http://snomed.info/sct"](http://snomed.info/sct%22),

                "code": "402356004",

                "display": "Chronic graft-versus-host disease"

            }

        ]

    },`

**Comment by gcangioli** [comment]
Hi @davisart can you help me to better understand your question ? In my understanding acute and chronic are mutually exclusive _(Acute GVHD (aGVHD) usually occurs <100 days after HCT, while chronic GVHD (cGVHD) usually occurs ≥100 days after HCT)_

let's clarify this in a call

**Comment by davisart** [comment]
no, they can occur together, this is the confirmation from Monica (Gaslini):
- invece per il trapianto posso dirti che si tratta di due domande svincolate dalla profilassi. Il paziente può fare la profilassi e comunque sviluppare la GVHD acuta e/o cronica


howewer we need to know if both codes go within the same "coding" father as shown in the example

**Comment by gcangioli** [comment]
In principle you can have more coding in a same code to represent the _"same"_ concept with different code concepts.

In that case you're capturing two distinct conditions the acute and the chronic gvdh, so you should have two separate condition resources.

**Comment by gcangioli** [comment]
to do:
conditionDueto

- codeableConcept 0..0
- reference 1..1
