### ISSUE TITLE
FLT: Randomization Arm for Trial Extension

### ISSUE THREAD

**Issue by StefanBeyer** [hl7-eu/pcsp#49]
According to the [extension for the randomization arm for trials](http://build.fhir.org/ig/hl7-eu/pcsp/StructureDefinition-procedure-fltArm.html) and the [procedure profile for front line treatment](http://build.fhir.org/ig/hl7-eu/pcsp/StructureDefinition-Procedure-flt-eu-pcsp.html), the extension should be added to the procedure resource.

However in the [FLT logical model mapping](http://build.fhir.org/ig/hl7-eu/pcsp/StructureDefinition-FrontLineTreatment-mappings.html) and the current PCSP implementation, the extension should be added to the plan definition resource.

Which one is the correct way? Could you please clarify.

**Comment by gcangioli** [comment]
Hi @StefanBeyer I agree with your statement, I mean this information should be in the CarePlanDefiniton.

If @davisart confirm that this is how it is now implemented I'll fix it in the profile/extension

In any case the mapping 
followedProtocol => PlanDefinition.conformsTo('http://hl7.eu/fhir/ig/pcsp/StructureDefinition/PlanDefinition-flt-eu-pcsp'), .instantiatesCanonical
shall be changed into .instantiatesCanonical.resolve()

**Comment by gcangioli** [comment]
Change applied in https://github.com/hl7-eu/pcsp/commit/aa254dbcf21c05c43f7aac22f86c24edd5fa543d

**Comment by davisart** [comment]
we confirm the information of arm is in PlanDefinition resource which is linked in FLT Procedure (http://build.fhir.org/ig/hl7-eu/pcsp/StructureDefinition-Procedure-flt-eu-pcsp.html)
