### ISSUE TITLE
Pseudonymized DOB

### ISSUE THREAD

**Issue by StefanBeyer** [hl7-eu/pcsp#51]
As you might know, we are going to send the data in a pseudonymized way to the platform.

We were wondering how we could send the birthdate, so that it cannot be used to reidentify the patient and still be correct (as this is a mandatory field for the care plan generation and probably influences the resulting care plan).

Our idea would be to only send the current age information (in years). As we immediately generate the care plan and the patient info is deleted afterwards, this info should never become stale.

From our point of view, this could be achieved in two ways:
1. Generate a fake birth date (e.g. calculate the age of the patient, subtract it from the current date and subtract X additional days/months, maybe even round to a month/quarter) => all patients of the same age would have the same birthdate, only varying by the day/month/quarter where the data is sent
2. Use a different field than [dateOfBirth](http://build.fhir.org/ig/hl7-eu/pcsp/StructureDefinition-Subject-definitions.html#diff_Subject.dateOfBirth) to only send the age of the patient. Is there a FHIR way of sending the birth date in a pseudonymized way? I am not aware of any.

What are your thoughts about this? @davisart how is the date of birth currently processed with regards to the care plan recommendations?

**Comment by gcangioli** [comment]
DOB is not a required element in the base Patient resource, but is is required by the IPS patient profile.

You are allowed to send only the year, not clear to me what you mean with "fake birth date" .

The age is usually used associated to an event e.g. age of onset or resolution of a condition; or age of death;... for the Patient resource the age makes a little sense...

if you don't want to provide the DOB and be still compliant with the current profile you can still use the data-absent-reason extension

**Comment by StefanBeyer** [comment]
I see. We just want to make sure that we don't loose any important information in the generated care plan, especially concerning recommendations, if we don't send this information (or only send the year).

By fake birth date I just mean an obfuscated birth date which still correctly depicts the age (with some vagueness, but still a little bit more precise than just sending the year).

If we don't loose any important information, I guess we would prefer sending the data-absent-reason.

**Comment by StefanBeyer** [comment]
For future reference: we will send the year only, as this influences at least one recommendation in the care plan. It is not necessarry to send this information with more granularity, according to the clinical experts.
