### ISSUE TITLE
CarePlan Resource - Unselected recommendations

### ISSUE THREAD

**Issue by davisart** [hl7-eu/pcsp#52]
During the validation process, the surpass platform allows the clinician to deselect recommendations that do not make sense for the patient (for example, the patient already has a heart problem, so the relative recommendation would be superfluous)

We would like to know if we can use the CarePlan.activity.status variable using the codes:
1) selected
2) unselected
To determine if a recommendations has been triggered by the platform but unselected from clinician.

This rule does not apply to Preliminary Care Plans made with the API (they will all stay selected)

Thank you!

**Comment by gcangioli** [comment]
Yes the status is the right element, however you cannot use selected/unselected.

The binding with the value set http://hl7.org/fhir/R4/valueset-care-plan-activity-status.html is of type required.

for unselected you could use 	cancelled	"The planned care plan activity has been withdrawn." 
Other coherent statuses (e.g. not-started) for selected.

You can use the _statusReason_ for saying why it has been withdrawn e.g. unselected by the user.
