### ISSUE TITLE
Composition Resource - Elements: 1) RelapseDuringFLT and 2) CarePlan

### ISSUE THREAD

**Issue by davisart** [hl7-eu/pcsp#53]
In the Composition Resource (https://build.fhir.org/ig/hl7-eu/pcsp/StructureDefinition-Composition-surpass-eu-pcsp.html) maybe there are two elements missing :
1) RelapseDuringFLT
2) CarePlan

Is that right?
Thank you!
Davide

**Comment by gcangioli** [comment]
@davisart good catch :.. I'll keep you posted -)

**Comment by gcangioli** [comment]
@davisart 

- CarePlan added
- for the RelapseDuringFLT it seems to be a Condition.. let meet and discuss the general structure and finalize it..

**Comment by gcangioli** [comment]
RelapseDuringFLT is documented with a Condition resource in an entry of the FLT section

**Comment by gcangioli** [comment]
To do 

- [ ] create a slice for the FLT section to make more clear the usage of the primary cancer and relapse
