### ISSUE TITLE
Composition Resource: implementation info

### ISSUE THREAD

**Issue by davisart** [hl7-eu/pcsp#54]
We kindly ask if:

1) for surgery resource we need to link only the "father" resource or the children also?
2) same question for "radiotherapy"
3) for radiotherapy resource we need to link only the "base" resource or also the boost and shielding?

thank you

**Comment by gcangioli** [comment]
The composition should refer the "root" resources, you are not required to refer in the composition those referred by the "root resources", e.g. you refer the Procedure-sct-eu-pcsp and not BiologicallyDerivedProduct-sct-eu-pcsp
The  bundle includes on the contrary all the resources directly or indirectly referred by the composition

**Comment by gcangioli** [comment]
- [ ] BiologicallyDerivedProduct: Stem Cell
- [ ] Bundle: Survivor Passport
- [ ] CarePlan: PCSP
- [ ] Composition: Survivor Passport
- [ ] Condition: GvHD
- [ ] Condition: Metastatic Cancer
- [ ] Condition: Others
- [ ] Condition: Primary Cancer
- [ ] Condition: Severe Toxicity
- [ ] DocumentReference: PCSP
- [ ] Encounter: Treatment Center
- [ ] Location: Location PCSP
- [ ] MedicationAdministration: Chemotherapy
- [ ] MedicationStatement: Chemotherapy
- [ ] Observation: Blood type/RH
- [ ] Observation: Cancer Stage Group
- [ ] Observation: Chemotherapy Cumulative Dose
- [ ] Observation: Condition: Secondary Cancer
- [ ] Observation: Diagnosis details
- [ ] Observation: Hereditary Predisposition
- [ ] Observation: Radiotherapy Total Dose PCSP
- [ ] Observation: Risk Factor
- [ ] Observation: TNM Primary Tumor Category
- [ ] Observation: TNM Regional Nodes Category
- [ ] Organization: Primary Treatment Center / Center of diagnosis
- [ ] Patient: Patient PCSP
- [ ] PlanDefinition: Front Line Treatment
- [ ] Procedure: Catheter
- [ ] Procedure: Cryopreservation
- [ ] Procedure: Front Line Treatment
- [ ] Procedure: Other Treatments
- [ ] Procedure: Radiotherapy
- [ ] Procedure: Radiotherapy Boost
- [ ] Procedure: Radiotherapy Shielding
- [ ] Procedure: SCT Prophylaxis
- [ ] Procedure: Stem Cell Transplantation
- [ ] Procedure: Surgery
- [ ] Procedure: Transfusion other infos

**Comment by gcangioli** [comment]
Add references for these profiles

- [ ]  Condition: Severe Toxicity
- [ ]  Add references to these profiles
- [ ] Condition: Others
- [ ]  Procedure: Catheter
- [ ]  Procedure: Cryopreservation
- [ ]  Procedure: Other Treatments
- [ ]  Procedure: Transfusion other infos
