### ISSUE TITLE
Update the riskfactor code systeme / value set

### ISSUE THREAD

**Issue by gcangioli** [hl7-eu/pcsp#60]
Update the risk factor code system and value set according to the revised table provided with the Davide's email of Feb 16th

**Comment by gcangioli** [comment]
@davisart :please check duplicated items 

* #4.2 "RT to a vol exposing the testes" "RT to a vol exposing the testes"
// * #4.2 "RT to a vol exposing the testes or pelvis" "RT to a vol exposing the testes or pelvis"
* #4.3 "Including TBI" "Including TBI"
// * #4.3 "Any radiotherapy including TBI" "Any radiotherapy including TBI"
* #40.1 "RT to a vol exposing the lungs" "RT to a vol exposing the lungs"
// * #40.1 "RT to a vol exposing the oral cavity" "RT to a vol exposing the oral cavity"

**Comment by gcangioli** [comment]
@davisart please check

**Comment by davisart** [comment]
The list has been rectified on the repository
